"""Init

Revision ID: d35604898509
Revises: fce9c54c61fc
Create Date: 2023-03-03 18:22:09.435877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35604898509'
down_revision = 'fce9c54c61fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Contacts', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Contacts', type_='foreignkey')
    op.drop_column('Contacts', 'user_id')
    # ### end Alembic commands ###
